name: ~ build

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true

jobs:
  builder:
    name: builder image
    runs-on: ubuntu-22.04
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Build Postgres Image for linux/amd64'
        run: |
          docker build \
            -f Dockerfile.postgres \
            --platform linux/amd64 \
            -t ghcr.io/trycompa/postgres:${{ inputs.tag }}-linux-amd64 \
            --push .

      - name: 'Build Postgres Image for linux/arm64'
        run: |
          docker buildx build \
            -f Dockerfile.postgres \
            --platform linux/arm64 \
            -t ghcr.io/trycompa/postgres:${{ inputs.tag }}-linux-arm64 \
            --push .

      - name: 'Build Postgres Multi-Architecture Image'
        run: |
          docker buildx build \
            -f Dockerfile.postgres \
            --platform linux/amd64,linux/arm64 \
            -t ghcr.io/trycompa/postgres:${{ inputs.tag }} \
            --push .
